//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace lang
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class InvalidLanguageFileException : Exception
	{
		private int errorIndex
		{
			get;
			set;
		}

		private string errorKey
		{
			get;
			set;
		}

		private IEnumerable<string> keys
		{
			get;
			set;
		}

		public virtual int getErrorIndex()
		{
			throw new System.NotImplementedException();
		}

		public virtual string getErrorKey()
		{
			throw new System.NotImplementedException();
		}

		public virtual IEnumerable<string> getKeys()
		{
			throw new System.NotImplementedException();
		}

		public virtual void constructor(int errorIndex, string errorKey, IEnumerable<string> keys)
		{
			throw new System.NotImplementedException();
		}

	}
}

